<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Kirim Perbaharui Status Penjualan</name>
   <tag></tag>
   <elementGuidId>da2e439f-4f1f-4d3b-a5af-d2926e519720</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#statusModal90044 > div.modal-dialog.modal-dialog-centered > form.modal-content.px-4.py-2 > div.modal-footer.border-0 > input[name=&quot;commit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='commit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>803d700b-5a33-4cb5-a108-5a3de09ad5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f0ed426e-f03b-4309-b79d-99785acf7ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>commit</value>
      <webElementGuid>fa52ee98-9e88-48b4-85f1-8b4da9ea9baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Kirim</value>
      <webElementGuid>097cf451-34bc-48f2-ae68-a8f540c6786e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary p-3 w-100 rounded-4 fw-bold</value>
      <webElementGuid>295b9b3f-a5e7-4e16-ab08-8405ca09efd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disable-with</name>
      <type>Main</type>
      <value>Kirim</value>
      <webElementGuid>bdac5af3-82e5-4ab2-9cb9-a3740b14723e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;statusModal90044&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/form[@class=&quot;modal-content px-4 py-2&quot;]/div[@class=&quot;modal-footer border-0&quot;]/input[@class=&quot;btn btn-primary p-3 w-100 rounded-4 fw-bold&quot;]</value>
      <webElementGuid>a61c54cb-ac4d-4e55-8d32-7e3eef703b5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='commit'])[2]</value>
      <webElementGuid>49f29f9d-978a-4e3e-8a93-04c5519b84b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='statusModal90044']/div/form/div[3]/input</value>
      <webElementGuid>3f3b66c8-0622-4a17-b66e-9a6dd16f2268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[3]/input</value>
      <webElementGuid>ab55d48f-2531-44a7-a82c-7955cd732ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'commit']</value>
      <webElementGuid>2050b8be-d1ba-4b93-85ea-0e8a60817237</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
