<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Harga Tawar_offerprice</name>
   <tag></tag>
   <elementGuidId>86ce0131-fd34-49d4-8096-2a4dceaae943</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#offer_price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='offer_price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>857d3436-db63-471f-9041-bd0a26c23bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control rounded-4 p-3</value>
      <webElementGuid>600410b9-8e35-45dc-adef-6f96085654ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rp 0,00</value>
      <webElementGuid>b6bf80cc-9137-44f2-8869-f548f41ab012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>417d471b-30c7-4c9b-b123-9bfd36a72b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.0</value>
      <webElementGuid>a15b737e-5964-45ad-9b1e-6554371d511e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>offer[price]</value>
      <webElementGuid>42136bdf-072d-4b67-9e00-3c2030cd02a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>offer_price</value>
      <webElementGuid>6e037363-4663-4586-bf52-875158e45cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;offer_price&quot;)</value>
      <webElementGuid>bfe1fb6e-55f9-4ff4-a856-902b9a354084</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='offer_price']</value>
      <webElementGuid>3b715e0a-2162-4d76-bcbe-03263d47962f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='offerModal']/div/form/div[2]/div[2]/input</value>
      <webElementGuid>9c4fbe6d-24e0-442c-8700-00c0415bb717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>877f381e-53d4-4d42-8f77-3daa7f5f9ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Rp 0,00' and @type = 'number' and @name = 'offer[price]' and @id = 'offer_price']</value>
      <webElementGuid>81b82864-49bf-49ad-9017-194ec3e1cc8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
